<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="first.local" failures="1" tests="2" name="runner.driverRunner" time="20.006" errors="0" timestamp="2024-02-07T21:25:30 IST" skipped="0">
  <testcase classname="runner.driverRunner" name="runScenario" time="7.979"/>
  <testcase classname="runner.driverRunner" name="runScenario" time="12.027">
    <failure message="expected [https://www.saucedemo.com/inventory.htm] but found [https://www.saucedemo.com/inventory.html]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.htm] but found [https://www.saucedemo.com/inventory.html]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDef.productScreenTest.return_back_to_product_page(productScreenTest.java:46)
at âœ½.return back to product page(file:///Users/varadharajan/git/Sauce/SauceLabDemo/src/main/java/sauce/feature/productsPage.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.driverRunner -->
